import type { ResearchPaper } from './researchShowcase';

// Original arXiv submission dates, verified 2026-09-09. Known MAIA coauthors only.
export const RESEARCH_UPDATES: ResearchPaper[] = [
	{ title: "Underwriting the Agent Economy: The Blueprint for an AI Insurance Stack", authors: ["Stephen Casper"], date: '2026-07-13', description: "Examines how insurance could price and manage AI-agent risks, and the coordination needed to make meaningful coverage possible.", link: 'https://arxiv.org/abs/2607.11999' },
	{ title: "The 2026 Singapore Consensus on Global AI Safety Research Priorities", authors: ["Stephen Casper"], date: '2026-07-09', description: "Identifies shared technical safety priorities, with a focus on autonomous agents and societal resilience.", link: 'https://arxiv.org/abs/2608.14611' },
	{ title: "How Transparent is DiffusionGemma?", authors: ["Josh Engels"], date: '2026-06-18', description: "Studies reasoning transparency in diffusion models and tests an interpretable token bottleneck between denoising steps.", link: 'https://arxiv.org/abs/2606.20560' },
	{ title: "There Will Be a Scientific Theory of Deep Learning", authors: ["Eric J. Michaud"], date: '2026-04-23', description: "Connects emerging theories of training dynamics, representations, and scaling into a proposed mechanics of learning.", link: 'https://arxiv.org/abs/2604.21691' },
	{ title: "International AI Safety Report 2026", authors: ["Stephen Casper"], date: '2026-02-24', description: "Reviews the evidence on general-purpose AI capabilities, emerging risks, and safeguards in the second international report.", link: 'https://arxiv.org/abs/2602.21012' },
	{ title: "The 2025 AI Agent Index: Documenting Technical and Safety Features of Deployed Agentic AI Systems", authors: ["Stephen Casper"], date: '2026-02-19', description: "Documents 30 deployed AI agents and compares the transparency of their capabilities, evaluations, and safety practices.", link: 'https://arxiv.org/abs/2602.17753' },
	{ title: "Expanding External Access To Frontier AI Models For Dangerous Capability Evaluations", authors: ["Stephen Casper"], date: '2026-01-17', description: "Proposes a framework for evaluator access to models, information, and evaluation time, including the benefits and risks of each level.", link: 'https://arxiv.org/abs/2601.11916' },
	{ title: "Frontier AI Auditing: Toward Rigorous Third-Party Assessment of Safety and Security Practices at Leading AI Companies", authors: ["Stephen Casper"], date: '2026-01-16', description: "Sets out assurance levels and practical requirements for independent audits of frontier developers and their safety practices.", link: 'https://arxiv.org/abs/2601.11699' },
	{ title: "Internal Deployment Gaps in AI Regulation", authors: ["Stephen Casper"], date: '2026-01-12', description: "Examines regulatory blind spots for internally deployed AI systems and outlines approaches to oversight.", link: 'https://arxiv.org/abs/2601.08005' },
	{ title: "Legal Alignment for Safe and Ethical AI", authors: ["Stephen Casper"], date: '2026-01-07', description: "Surveys how legal rules, interpretive methods, and institutional concepts can inform safe and ethical AI behavior.", link: 'https://arxiv.org/abs/2601.04175' }
];
